# Generated by Django 5.0.2 on 2024-03-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForYouItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.IntegerField(default=0)),
                ('ImageSrc', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
