# Generated by Django 5.0.2 on 2024-03-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_homeitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeItems',
            new_name='Fruits_Vegetables',
        ),
    ]
