# Generated by Django 5.0.2 on 2024-03-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_rename_homeitems_fruits_vegetables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atta_Oil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.IntegerField(default=0)),
                ('ImageSrc', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dairy_Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.IntegerField(default=0)),
                ('ImageSrc', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Frozen_Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.IntegerField(default=0)),
                ('ImageSrc', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Masala_Dryfruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.IntegerField(default=0)),
                ('ImageSrc', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Packed_Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.IntegerField(default=0)),
                ('ImageSrc', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sweet_Craving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.IntegerField(default=0)),
                ('ImageSrc', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
