# Generated by Django 5.0.2 on 2024-03-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_bath_body_hair_biscuits_cookies_breakfast_sauces_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby_Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.IntegerField(default=0)),
                ('ImageSrc', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.IntegerField(default=0)),
                ('ImageSrc', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.IntegerField(default=0)),
                ('ImageSrc', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grooming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.IntegerField(default=0)),
                ('ImageSrc', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Home_Needs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.IntegerField(default=0)),
                ('ImageSrc', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hygiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.IntegerField(default=0)),
                ('ImageSrc', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paan_Corner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.IntegerField(default=0)),
                ('ImageSrc', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pet_Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.IntegerField(default=0)),
                ('ImageSrc', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Info', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField(default=0)),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
